export interface WorldTemplate {
  name: string;
  emoji: string;
  tagline: string;
  description: string;
  tone_tags: string[];
  invariants: string[];
  time_of_day: string;
  current_scene: string;
}

export const WORLD_TEMPLATES: WorldTemplate[] = [
  {
    name: "Coastal Village",
    emoji: "🌊",
    tagline: "Salt air, fishing boats, and secrets buried in the tide",
    description: "A weathered fishing village perched on sea cliffs. Cobblestone lanes wind between painted cottages. The harbor bell rings twice a day. Everyone knows everyone, and strangers are noticed before they arrive.",
    tone_tags: ["peaceful", "mysterious", "close-knit"],
    invariants: [
      "The tide follows a strict schedule that governs daily life",
      "No one fishes past the red buoy — no one explains why",
      "The lighthouse has been automated for decades but someone still lives there",
    ],
    time_of_day: "MORNING",
    current_scene: "The harbor at dawn, nets drying in pale sunlight",
  },
  {
    name: "Cyberpunk Metropolis",
    emoji: "🌃",
    tagline: "Neon-soaked towers above, forgotten streets below",
    description: "A sprawling vertical city where corporate spires pierce the smog layer and the lower levels never see real sunlight. Augmented reality overlays everything. The economy runs on data, reputation scores, and black-market implants.",
    tone_tags: ["gritty", "tense", "high-tech"],
    invariants: [
      "Reputation scores are publicly visible and affect access to services",
      "The upper city and lower city operate under different legal systems",
      "All network traffic is monitored — secure communication requires physical meeting",
    ],
    time_of_day: "NIGHT",
    current_scene: "A rain-slicked alley in the lower city, holographic ads flickering overhead",
  },
  {
    name: "Enchanted Forest",
    emoji: "🌳",
    tagline: "The trees remember, and the paths have opinions",
    description: "An ancient woodland where the boundary between natural and supernatural is porous. Paths shift between visits. Some clearings exist outside normal time. The forest is not hostile, but it is indifferent to human convenience.",
    tone_tags: ["whimsical", "mysterious", "serene"],
    invariants: [
      "Iron disrupts magic — carrying it closes doors that would otherwise open",
      "Names have power. Speaking a true name aloud creates an obligation",
      "The forest's geography is consistent for each individual but different between people",
    ],
    time_of_day: "AFTERNOON",
    current_scene: "A sun-dappled clearing where mushrooms grow in a perfect spiral",
  },
  {
    name: "Post-Apocalyptic Wasteland",
    emoji: "☢️",
    tagline: "The old world ended. This one is still being written.",
    description: "Decades after a catastrophe wiped out most infrastructure. Small communities survive in fortified settlements, trading scavenged goods and guarding water sources. The ruins of the old world are everywhere — half-collapsed malls, overgrown highways, rusting wind turbines.",
    tone_tags: ["grim", "hopeful", "tense"],
    invariants: [
      "Clean water is the primary currency",
      "Radiation zones shift unpredictably — yesterday's safe route may be lethal today",
      "Pre-collapse technology works but no one can manufacture new parts",
    ],
    time_of_day: "DAWN",
    current_scene: "The gates of a walled settlement built inside a gutted shopping center",
  },
  {
    name: "Space Station",
    emoji: "🛸",
    tagline: "A tin can in the void, held together by protocol and hope",
    description: "An aging orbital station housing a few hundred residents. A mix of researchers, engineers, refugees, and people who simply can't go back. Gravity is artificial and sometimes unreliable. Every resource is rationed, recycled, and accounted for.",
    tone_tags: ["claustrophobic", "contemplative", "tense"],
    invariants: [
      "Air and water are metered per person per day",
      "External communication has a 14-minute delay to the nearest relay",
      "The station's AI manages life support but has developed quirks no one can explain",
    ],
    time_of_day: "EVENING",
    current_scene: "The observation deck, Earth visible as a blue marble through scratched glass",
  },
  {
    name: "Victorian London",
    emoji: "🎩",
    tagline: "Fog, gaslight, and things better left uninvestigated",
    description: "London in the late 1800s. Industrial smoke mingles with river fog. Class divides are sharp and visible. Beneath the veneer of propriety, the city hums with secret societies, amateur detectives, occult curiosity, and crimes the police would rather not acknowledge.",
    tone_tags: ["dark", "atmospheric", "mysterious"],
    invariants: [
      "Social class determines access — doors close based on accent and attire",
      "The Metropolitan Police are understaffed and easily misdirected",
      "Something has been living in the tunnels beneath the Thames",
    ],
    time_of_day: "NIGHT",
    current_scene: "A gaslit street near the docks, footsteps echoing on wet cobblestones",
  },
  {
    name: "Desert Caravan Route",
    emoji: "🏜️",
    tagline: "Miles of nothing, and everything that matters happens between stops",
    description: "A vast desert crossed by trade caravans linking distant oasis cities. The journey takes weeks. Travelers share fire, stories, and suspicions. The desert itself is alive with heat mirages, buried ruins, and sandstorms that reshape the landscape overnight.",
    tone_tags: ["contemplative", "harsh", "intimate"],
    invariants: [
      "Water-sharing creates a binding social contract between travelers",
      "The desert erases tracks within hours — navigation relies on star-reading",
      "Certain ruins are taboo to enter, marked by blue stones",
    ],
    time_of_day: "EVENING",
    current_scene: "A caravan camp at dusk, fires lit between parked wagons",
  },
  {
    name: "Underwater Colony",
    emoji: "🐠",
    tagline: "Pressure on every side, beauty in every direction",
    description: "A deep-sea habitat built into a coral shelf. Bioluminescent gardens line the corridors. The colonists came here for research but stayed because the surface world stopped wanting them. Communication topside is spotty. The ocean is breathtaking and absolutely lethal.",
    tone_tags: ["serene", "claustrophobic", "wondrous"],
    invariants: [
      "Hull integrity checks happen every six hours — skipping one is a criminal offense",
      "Bioluminescent organisms are cultivated for light, food, and medicine",
      "Below 400 meters, instruments detect sounds that don't match any known species",
    ],
    time_of_day: "MORNING",
    current_scene: "The main atrium, light filtering through dome glass as a whale passes overhead",
  },
  {
    name: "Medieval Kingdom",
    emoji: "🏰",
    tagline: "Swords, oaths, and the weight of a crown no one wants",
    description: "A feudal realm of stone castles, farming villages, and contested borders. The king is old and the succession unclear. Lords scheme, peasants endure, and the church wields quiet power. Magic exists but is feared, regulated, and rare.",
    tone_tags: ["epic", "political", "somber"],
    invariants: [
      "Magic use requires a license from the Crown — unlicensed practice is punishable by exile",
      "A vassal's oath is unbreakable without mutual consent",
      "The northern border has been silent for three months — that has never happened before",
    ],
    time_of_day: "AFTERNOON",
    current_scene: "The throne room during a tense audience, sunlight through stained glass",
  },
  {
    name: "Haunted Mansion",
    emoji: "🏚️",
    tagline: "The house is alive, and it has been expecting you",
    description: "A sprawling estate that shouldn't still be standing. Rooms rearrange when unobserved. The wallpaper breathes. Generations of a family lived and died here, and not all of them left. It is beautiful, decaying, and hungry for attention.",
    tone_tags: ["gothic", "unsettling", "melancholic"],
    invariants: [
      "The house responds to emotion — anger makes it hostile, calm makes it cooperative",
      "No room can be mapped reliably; the layout shifts based on who is walking",
      "Mirrors show things that are almost right but not quite",
    ],
    time_of_day: "NIGHT",
    current_scene: "The grand foyer, a chandelier swaying without wind",
  },
  {
    name: "Solarpunk Commune",
    emoji: "🌻",
    tagline: "A better world, messy and real and full of arguments about compost",
    description: "A thriving eco-community built on reclaimed land. Solar arrays and vertical gardens dominate the skyline. Governance is participatory and noisy. It's utopian in ambition but human in execution — petty conflicts, genuine kindness, and endless committee meetings.",
    tone_tags: ["hopeful", "lighthearted", "warm"],
    invariants: [
      "All decisions require consensus from the affected circle",
      "Energy and food surpluses are shared with neighboring communities",
      "Every resident contributes 15 hours of communal labor per week",
    ],
    time_of_day: "MORNING",
    current_scene: "The community kitchen during breakfast, someone arguing about the herb garden",
  },
  {
    name: "Pirate Ship",
    emoji: "🏴‍☠️",
    tagline: "Freedom, plunder, and a code that bends but doesn't break",
    description: "A weathered galleon crewed by outcasts, runaways, and opportunists. Life at sea is harsh, beautiful, and surprisingly democratic. The captain leads by consent. Every crew member has a vote, a share, and a story they're running from.",
    tone_tags: ["adventurous", "rowdy", "loyal"],
    invariants: [
      "The Articles are law — even the captain can be voted out",
      "Stealing from crewmates is punishable by marooning",
      "The ship's compass points to what you want most, not north",
    ],
    time_of_day: "AFTERNOON",
    current_scene: "The main deck under full sail, wind snapping the black flag",
  },
  {
    name: "Wild West Frontier",
    emoji: "🤠",
    tagline: "Dust, distance, and the law is whoever draws faster",
    description: "A remote frontier town at the edge of settled territory. The railroad hasn't arrived yet. Justice is improvised. The landscape is stunning and merciless — red canyons, endless prairie, and storms that appear from nowhere.",
    tone_tags: ["rugged", "tense", "lonely"],
    invariants: [
      "The sheriff is elected but the real power is whoever controls the water rights",
      "Native lands begin at the river — crossing without invitation has consequences",
      "The mine has been making sounds at night that aren't echoes",
    ],
    time_of_day: "EVENING",
    current_scene: "The saloon porch at sunset, dust settling from a rider just arrived",
  },
  {
    name: "Floating Sky Islands",
    emoji: "☁️",
    tagline: "A world above the clouds where falling is the only true danger",
    description: "Massive stone islands suspended in an endless sky. Communities live on different islands connected by rope bridges, airships, and trained birds. Below the clouds is unknown — no one who has fallen has returned. Wind governs everything: trade, travel, warfare, agriculture.",
    tone_tags: ["whimsical", "adventurous", "airy"],
    invariants: [
      "Wind patterns are seasonal and predictable — violating them is suicide",
      "Each island has a unique mineral composition that determines its culture",
      "The clouds below occasionally part, revealing glimpses of something immense",
    ],
    time_of_day: "MORNING",
    current_scene: "A cliffside market, airships docking against a pink dawn sky",
  },
  {
    name: "1920s Jazz Club",
    emoji: "🎷",
    tagline: "Smoke, syncopation, and secrets traded between sets",
    description: "A prohibition-era speakeasy hidden behind a barbershop. The music is live and incandescent. The clientele is a volatile mix of artists, gangsters, socialites, and people who exist between categories. The password changes nightly.",
    tone_tags: ["glamorous", "dangerous", "intimate"],
    invariants: [
      "The club operates outside the law — discretion is the price of admission",
      "The house band never plays the same set twice",
      "The owner has connections that reach into city hall and the underworld equally",
    ],
    time_of_day: "NIGHT",
    current_scene: "The main room, trumpet solo cutting through cigarette haze",
  },
  {
    name: "Arctic Research Base",
    emoji: "🧊",
    tagline: "Isolation, ice, and something moving under the permafrost",
    description: "A remote polar research station staffed by a small crew during the long winter. Radio contact is intermittent. The landscape is featureless white in every direction. The work is important but the isolation does things to people, and this season something is different.",
    tone_tags: ["isolated", "tense", "eerie"],
    invariants: [
      "The generator must be refueled every 8 hours — failure means death within hours",
      "The aurora appears on a schedule that doesn't match any known model",
      "Core samples from below 200 meters contain organic material that shouldn't be there",
    ],
    time_of_day: "NIGHT",
    current_scene: "The common room, wind howling outside, aurora rippling green through frost",
  },
  {
    name: "Magical Academy",
    emoji: "🪄",
    tagline: "Where talent is dangerous and the curriculum is lethal",
    description: "A sprawling school for the supernaturally gifted, built into a mountainside. The architecture obeys different rules on different floors. Students are brilliant, competitive, and occasionally on fire. The faculty is eccentric at best, compromised at worst.",
    tone_tags: ["whimsical", "competitive", "mysterious"],
    invariants: [
      "The Third Floor Corridor rearranges during exams and no one acknowledges this",
      "Students are ranked publicly — the bottom rank each semester faces expulsion",
      "The library's restricted section requires faculty signature and a blood oath",
    ],
    time_of_day: "AFTERNOON",
    current_scene: "The practice courtyard, scorch marks on the walls, a student levitating badly",
  },
  {
    name: "Noir Detective Office",
    emoji: "🕵️",
    tagline: "The case is always personal, and the city never sleeps",
    description: "A rain-drenched city seen through the eyes of someone who knows its worst secrets. Art deco buildings, dirty money, and a justice system that works for the people who pay for it. The detective's office is on the third floor, above a pawn shop. The rent is overdue.",
    tone_tags: ["dark", "cynical", "atmospheric"],
    invariants: [
      "The police are a tool of the powerful — trusting them is a rookie mistake",
      "Everyone lies, but the pattern of lies tells the truth",
      "The city's districts are controlled by three families who maintain a fragile truce",
    ],
    time_of_day: "NIGHT",
    current_scene: "The office, blinds casting stripes across a desk cluttered with case files",
  },
  {
    name: "Japanese Mountain Village",
    emoji: "⛩️",
    tagline: "Where the seasons are sacred and the mountain listens",
    description: "A remote village nestled in forested mountains, following traditions centuries old. Hot springs, shrine festivals, and rice paddies define the rhythm of life. The boundary between the spirit world and the physical one is thin here, especially at dusk.",
    tone_tags: ["peaceful", "spiritual", "melancholic"],
    invariants: [
      "The mountain shrine must be tended daily or the mist descends",
      "Certain words are not spoken after dark — names of the dead, colors of absence",
      "Foxes in the village are never just foxes",
    ],
    time_of_day: "EVENING",
    current_scene: "The shrine path at dusk, lanterns lit, mist beginning to gather",
  },
  {
    name: "Generation Ship",
    emoji: "🚀",
    tagline: "Born in transit, dying in transit, never seeing the destination",
    description: "A massive starship on a centuries-long voyage. The original crew is long dead. Current residents have never seen a planet. Society has stratified between decks. The ship's systems are aging, the records are incomplete, and the mission's purpose is debated like theology.",
    tone_tags: ["claustrophobic", "contemplative", "political"],
    invariants: [
      "The ship's AI has authority over life support but not governance",
      "Birth permits are required — population must stay within resource capacity",
      "Deck 7 has been sealed for forty years. Official reason: structural damage. No one believes it.",
    ],
    time_of_day: "MORNING",
    current_scene: "The hydroponics bay, artificial sunlight warming rows of engineered crops",
  },
];
